ARG CUDA="11.2.0"
ARG UBUNTU="18.04"
ARG ARCH=""
ARG CUDNN="-cudnn8" # needs '-' to get level right if blank.

FROM nvidia/cuda${ARCH}:${CUDA}${CUDNN}-devel-ubuntu${UBUNTU}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y &&\
    apt install software-properties-common -y &&\
    add-apt-repository ppa:deadsnakes/ppa &&\
    # Install build tools, build dependencies and python
    apt-get install -y \
    python3-pip \
    build-essential \
    cmake \
    git \
    libavcodec-dev \
    libavformat-dev \
    libavutil-dev \
    libeigen3-dev \
    libglew-dev \
    libgtk2.0-dev \
    libjpeg-dev \
    libpng-dev \
    libpostproc-dev \
    libpq-dev \
    libswscale-dev \
    libtbb2 \
    libtbb-dev \
    libtiff5-dev \
    libtiff-dev \
    libxine2-dev \
    pkg-config \
    unzip \
    wget \
    yasm \
    zlib1g-dev \
    ## Python
    python3-dev \
    python3-numpy \
    # python3.7-dev \
    ## Mediapipe
    ca-certificates \
    curl \
    ffmpeg \
    gcc-8 g++-8 \
    gfortran \
    libatlas-base-dev \
    libdc1394-22-dev \
    libegl1-mesa-dev \
    libgles2 \
    libgles2-mesa-dev \
    libgtk-3-dev \
    libhdf5-dev \
    libjpeg-dev \
    libpng-dev \
    libprotobuf-dev \
    libswscale-dev \
    libtbb2 \
    libtbb-dev \
    libtiff-dev \
    libv4l-dev \
    libx264-dev \
    libxvidcore-dev \
    mesa-common-dev \
    mesa-utils \
    openexr \
    pkg-config \
    protobuf-compiler \
    vim 

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100 --slave /usr/bin/g++ g++ /usr/bin/g++-8
RUN python3 -m pip install --upgrade pip setuptools

# Install bazel
ARG BAZEL_VERSION=3.7.2
RUN mkdir /bazel && \
    wget --no-check-certificate -O /bazel/installer.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/b\
azel-${BAZEL_VERSION}-installer-linux-x86_64.sh" && \
    wget --no-check-certificate -O  /bazel/LICENSE.txt "https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE" && \
    chmod +x /bazel/installer.sh && \
    /bazel/installer.sh  && \
    rm -f /bazel/installer.sh

RUN rm -rf /tmp/* && rm -rf /var/lib/apt/lists/*

COPY tests /tmp
COPY . /mediapipe/
WORKDIR /mediapipe
RUN python3 -m pip install -r requirements.txt
RUN bash setup_opencv_cuda.sh

RUN python3 setup.py gen_protos
# RUN python3 setup.py bdist_wheel
RUN python3 setup.py install --link-opencv

# For Application
RUN python3 pip install pandas scipy


# docker run -it --gpus all -e LOCAL_USER_ID=`id -u` --device=/dev/video0:/dev/video0 --volume="$PWD:/tmp/input_video" mediapipe:cuda bash 
# cd /home/dsw/source/github/pvc/battingcage
# docker run -it --gpus all -e LOCAL_USER_ID=`id -u` --volume="$PWD:/tmp/input_video" mediapipe:cuda2  python3 /tmp/input_video/process_one_swing.py

